services:
  fastapi:
    public: true
    image: kathleenfrancois/website:latest
    build: .
    replicas: 1
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres://katfran:katfran1@postgres:5432/katfran
      - secret=dev
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432
    environment:
      - POSTGRES_USER=katfran
      - POSTGRES_PASSWORD=katfran1
      - POSTGRES_DB=katfran
    volumes:
      - data:/bitnami/postgresql
volumes:
  data:
