services:
  fastapi:
    public: true
    image: kathleenfrancois/website:latest
    build: .
    replicas: 1
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres://pguserk:pgpassk@postgres:5432/pgdbk
      - secret=dev
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432
    environment:
      - POSTGRES_USER=pguserk
      - POSTGRES_PASSWORD=pgpassk
      - POSTGRES_DB=pgdbk
    volumes:
      - data:/bitnami/postgresql
volumes:
  data:
