services:
  fastapi:
    public: true
    image: kathleenfrancois/website:latest
    build: .
    replicas: 1
    ports:
      - 8080:8080
    environment:
      - DB_HOST=postgres://katmfran:passwordkf@postgres:5432/katfrancois
      - secret=dev
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - 5432
    environment:
      - POSTGRES_USER=katmfran
      - POSTGRES_PASSWORD=passwordkf
      - POSTGRES_DB=katfrancois
    volumes:
      - data:/bitnami/postgresql
volumes:
  data:
